times=60
logE=12
V=30
lambda=0.5
p=12
delay=0.5
ach=3



analyticalODE <- function(times,E,V,lambda,C01){
  t=seq(0,NROW(times)-2) #need to convert from times seconds to 0-maxtime, to allow comparison with the ODE solver # problem if lambda is a function of time
  data.frame(times=t,
             C=E/(V*lambda)*(1-exp(-lambda*t))+C01*exp(-lambda*t))
}

# AUC function -------------------------------------------------------

AUC <- function(x,y){ #To allow for non-uniform time-steps
  sum(diff(x[order(x)])*zoo::rollmean(y[order(x)],2))
}



# Exposure function -------------------------------------------------------
exposure<-function(logE,p,ach,times,delay){
  
  
  E <- (10^(logE))/3600
  #Find lambda which is the addtion of the removal rates
  lambda_v <- ach/3600 #1 ac/h, so divide by 3600 to get ac/s
  #half life of PsA 30 to 151 mins from "Viability of Pseudomonas aeruginosa in cough aerosols generated by persons with cystic fibrosis "
  half_life <- (30+ (runif(1)*121));
  half_life_s  <- half_life *60; #get in seconds
  lambda_i <- log(2)/half_life_s   #removal due to inactivation
  lambda_d  <- 0     #removal due to deposition
  lambda  <- 0.5 #lambda_v+lambda_i+lambda_d
  
  #Variable volume
  V <- 31.9+(runif(1)*11.8)  #area from all room sizes
  
  ####### Part 1 patient in the room
  
  t01=0
  tend1= as.numeric(times)*60 #X * 60 X is time in mins, to give seconds
  C01=0   #assume no intial concentration of CFU in the air
  
  times <- seq(t01, tend1, by = 1)
  parameters<-c(E,V,lambda)
  init<-c(C=C01)
  
  #out1 <- deSolve::lsoda(init, times = times, func = numerical_ODE, parms = parameters)%>% as_tibble()
  analyticalODE(times,E,V,lambda,C01)-> out1
  
  
  #l1=NROW(out[,1])
  #allC1[1:l1,i]=out[,2]
  #allt1[1:l1,i]=out[,1]
  #finalC1[1,i]=out[NROW(out[,2]),2]
  
  ###### Part 2 patient leaves the room
  
  #Intial conditions
  t02=tend1
  tend2= tend1 +(as.numeric(delay)*60); #X * 60 X is time in mins
  
  times <- seq(t02, tend2, by = 1)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0
  
  parameters<-c(0,V,lambda)
  init<-c(C=out1$C[NROW(out1)])
  #out2 <- deSolve::lsoda(init, times = times, func = numerical_ODE, parms = parameters)%>% as_tibble()
  
  analyticalODE(times,0,V,lambda,out1$C[NROW(out1)])-> out2
  
  ####### Part 3 susceptible patient enters room and breaths in CFU
  
  #Intial conditions
  #E0=0
  print(times)
  t03=tend2
  tend3= tend2 +as.numeric(tail(times, n=1))*60 #X * 60 X is time in mins
  #tspan2=[t02 tend2]
  print(tend3)
  
  times <- seq(t03, tend3, by = 1)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0

  
  parameters<-c(0,V,lambda)
  init<-c(C=out2$C[NROW(out2)])
  #out3 <- deSolve::lsoda(init, times = times, func = numerical_ODE, parms = parameters)%>% as_tibble()
  
  analyticalODE(times,0,V,lambda,out2$C[NROW(out2)])-> out3
  
  
  
  #for the AUC function
  #Inhaled particles
  tmp<-
    out3%>%
    summarise(dose=AUC(times,C*p))%>%
    mutate(risk=1-exp(-dose*as.numeric(410))) #Note the multiplication instead of division, this is because of how the dose-response parameter is given
  
  
  n_result<-data.frame(C1=out1$C[NROW(out1)],
                       C2=out2$C[NROW(out2)],
                       C3=out3$C[NROW(out3)],
                       dose=tmp$dose,
                       risk=tmp$risk
  )
  
  return(n_result)
  
}

q<-exposure(logE,p,ach,times,delay)