###TODO Every other concentration represents a patient, delay, times
###TODO add in other people
###TODO get line of best fit stats out

library(dplyr)
library(tidyr)
library(truncdist)
library(vroom)
library(janitor)
library(zoo)
library(shiny)
library(flexdashboard)
library(parallel)
library(ggplot2)
library(data.table)
library(DT)
library(personograph)
library(RColorBrewer)
library(plotly)
library(cowplot)



##### Finding Breathing rate, affecting emission rate
m<-1.52365; s<-1.151533
# Breathing rate
#p is in l/min
p1<-c(10.8,13.1,8.2,11.6,7.2,8.6,10.9,11.0,10.8,9.9,11.4,10.6,9.8,10.9,
      9.3,8.6,12.0,12.1,12.6,9.9)
p2=c(10.46, 11.48, 13.41, 16.13,16.55)
pval=c(p1,p2)
meanp=mean(pval)
stdp=sd(pval)
pmin=meanp-stdp
pmax=meanp+stdp
pdiff=pmax-pmin
SEM = stdp/sqrt(NROW(pval))             # Standard Error
ts =  qt(c(.025, .975), df=NROW(pval)-1)   # T-Score
CI = meanp + ts*SEM                     # Confidence Intervals

####### Inputs manually chosen

N=5
set.seed(42)
times<-runif(N,min = 10,max = 120)
ach=runif(N,min = 0.1,max = 6)
delay=runif(N,min = 1,max = 30)
k=runif(N,min = 1e-4,max = 1e-3)#rep(1e-4,N)
V =runif(N,min=10, max=40) 
logE = truncdist::rtrunc(n = N , spec = "norm" ,a = 0 ,b = 6, mean=m, sd=s)
p = ((CI[1]+runif(N)*CI[2]+runif(N))*0.001)/60 
half_life = 30+runif(N, min=0,max=121) #### half_life affects lambda which is removal rate
#half life of PsA 30 to 151 mins from "Viability of Pseudomonas aeruginosa in cough aerosols generated by persons with cystic fibrosis

#Find lambda which is the addtion of the removal rates
lambda_v <- ach/3600 #1 ac/h, so divide by 3600 to get ac/s
half_life_s  <- half_life*60; #get in seconds
lambda_i <- log(2)/half_life_s   #removal due to inactivation
lambda_d  <- 0     #removal due to deposition
lambda  <- lambda_v+lambda_i+lambda_d

### Numerical ODE

numerical_ODE<-function(t, state, parameters) {
  with(as.list(c(state, parameters)),{
    dC<-E/V-lambda*C
    list(dC)
  })
}


# Analytical Solution --------------------------------------------------------



analyticalODE <- function(times,E,V,lambda,C01){
  t=seq(0,NROW(times)-2) #need to convert from times seconds to 0-maxtime, to allow comparison with the ODE solver # problem if lambda is a function of time
  data.frame(times=t,
             C=E/(V*lambda)*(1-exp(-lambda*t))+C01*exp(-lambda*t))
}

# AUC function (Area Under Curve) -------------------------------------------------------


AUC <- function(x,y){ #To allow for non-uniform time-steps
  sum(diff(x[order(x)])*zoo::rollmean(y[order(x)],2))
}



# Exposure function -----------------------------------------------------
exposure<-function(logE,p,ach,times,delay,k,V,lambda){
  
  E <- (10^(logE))/3600
  
  #Variable volume
  #area from all room sizes
  
  ####### Part 1 patient in the room
  
  t01=0
  tend1= as.numeric(times)*60 #X * 60 X is time in mins, to give seconds
  C01=0   #assume no intial concentration of CFU in the air
  
  times <- mapply(":",t01,tend1)
  parameters<-c(E,V,lambda)
  init<-c(C=C01)
  
  analyticalODE(times,E,V,lambda,C01)-> out1
  
  ###### Part 2 patient leaves the room
  
  #Intial conditions
  t02=tend1
  tend2= tend1 +(as.numeric(delay)*60); #X * 60 X is time in mins
  
  times <- mapply(":",t02,tend2)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0
  
  parameters<-c(0,V,lambda)
  init<-c(C=out1$C[NROW(out1)])
  
  analyticalODE(times,0,V,lambda,out1$C[NROW(out1)])-> out2
  
  ####### Part 3 susceptible patient enters room and breaths in CFU
  
  #Intial conditions
  #E0=0
  t03=tend2
  tend3= tend2 +as.numeric(times)*60 #X * 60 X is time in mins
  #tspan2=[t02 tend2]
  times <- mapply(":",t03,tend3)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0
  
  parameters<-c(0,V,lambda)
  init<-c(C=out2$C[NROW(out2)])
  #out3 <- deSolve::lsoda(init, times = times, func = numerical_ODE, parms = parameters)%>% as_tibble()
  
  analyticalODE(times,0,V,lambda,out2$C[NROW(out2)])-> out3
  
  ####### Part 4 susceptible patient leaves room
  
  #Intial conditions
  #E0=0
  t04=tend3
  tend4= tend3 +as.numeric(delay)*60 #X * 60 X is time in mins
  #tspan2=[t02 tend2]
  times <- mapply(":",t04,tend4)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0
  
  parameters<-c(0,V,lambda)
  init<-c(C=out3$C[NROW(out3)])
  #out3 <- deSolve::lsoda(init, times = times, func = numerical_ODE, parms = parameters)%>% as_tibble()
  
  analyticalODE(times,0,V,lambda,out3$C[NROW(out3)])-> out4
  
  ####### Part 5 2nd susceptible patient enters room
  
  #Intial conditions
  #E0=0
  t05=tend4
  tend5= tend4 +as.numeric(times)*60 #X * 60 X is time in mins
  #tspan2=[t02 tend2]
  times <- mapply(":",t05,tend5)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0
  
  parameters<-c(0,V,lambda)
  init<-c(C=out4$C[NROW(out4)])
  #out3 <- deSolve::lsoda(init, times = times, func = numerical_ODE, parms = parameters)%>% as_tibble()
  
  analyticalODE(times,0,V,lambda,out4$C[NROW(out4)])-> out5
  
  tmp1<-
    out3%>%
    summarise(dose=AUC(times,C*p))%>%
    mutate(risk=1-exp(-dose*as.numeric(k))) #Note the multiplication instead of division, this is because of how the dose-response parameter is given
  
  tmp2<-
    out5%>%
    summarise(dose=AUC(times,C*p))%>%
    mutate(risk=1-exp(-dose*as.numeric(k))) #Note the multiplication instead of division, this is because of how the dose-response parameter is given
  
  
  exposure<-data.frame(C1=out1$C[NROW(out1)],
                       C2=out2$C[NROW(out2)],
                       C3=out3$C[NROW(out3)],
                       C4=out4$C[NROW(out4)],
                       C5=out5$C[NROW(out5)],
                       dose=tmp1$dose,
                       risk=tmp1$risk,
                       # dose=tmp2$dose,
                       # risk=tmp2$risk
  )
  
  return(exposure)
  
}

df=mcmapply(FUN = exposure,logE,p,ach,times,delay,k,V,lambda,mc.cores = 1) %>%
  t()%>%
  as.data.frame() %>%
  unnest(cols=c(C1, C2, C3, C4, C5, dose, risk))
#pivot_longer(!c(dose,risk))


df=cbind(df,logE,p,ach,times,delay,k,V,lambda)

plot(df)

p1 <- ggplot(df, aes(y=risk,x=ach))+
  geom_point(aes(y=risk,x=ach),alpha=0.2)+
  geom_smooth(aes(y=risk,x=ach),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p2 <- ggplot(df, aes(y=risk,x=V))+
  geom_point(aes(y=risk,x=V),alpha=0.2)+
  geom_smooth(aes(y=risk,x=V),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p3 <- ggplot(df, aes(y=risk,x=k))+
  geom_point(aes(y=risk,x=k),alpha=0.2)+
  geom_smooth(aes(y=risk,x=k),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p4 <- ggplot(df, aes(y=risk,x=delay))+
  geom_point(aes(y=risk,x=delay),alpha=0.2)+
  geom_smooth(aes(y=risk,x=delay),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p5 <- ggplot(df, aes(y=risk,x=times))+
  geom_point(aes(y=risk,x=times),alpha=0.2)+
  geom_smooth(aes(y=risk,x=times),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p6 <- ggplot(df, aes(y=risk,x=p))+
  geom_point(aes(y=risk,x=p),alpha=0.2)+
  geom_smooth(aes(y=risk,x=p),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p7 <- ggplot(df, aes(y=risk,x=logE))+
  geom_point(aes(y=risk,x=logE),alpha=0.2)+
  geom_smooth(aes(y=risk,x=logE),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

p8 <- ggplot(df, aes(y=risk,x=lambda))+
  geom_point(aes(y=risk,x=lambda),alpha=0.2)+
  geom_smooth(aes(y=risk,x=lambda),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()

plot_row <- plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, ncol = 4)

title <- ggdraw() + 
  draw_label(
    "Risk compared to Variables",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
plot_grid(
  title, plot_row,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 0.5)
)

# df %>% 
#   ggplot()+
#   geom_point(aes(y=risk,x=ach),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=ach),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()
# 
# df %>%
#   ggplot()+
#   geom_point(aes(y=risk,x=V),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=V),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()
# 
# df %>% 
#   ggplot()+
#   geom_point(aes(y=risk,x=k),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=k),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()
# 
# df %>% 
#   ggplot()+
#   geom_point(aes(y=risk,x=delay),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=delay),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()
# 
# df %>% 
#   ggplot()+
#   geom_point(aes(y=risk,x=times),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=times),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()
# 
# df %>% 
#   ggplot()+
#   geom_point(aes(y=risk,x=p),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=p),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()
# 
# df %>% 
#   ggplot()+
#   geom_point(aes(y=risk,x=logE),alpha=0.2)+
#   geom_smooth(aes(y=risk,x=logE),alpha=0.2,method="lm")+
#   hrbrthemes::theme_ipsum()


fit.lm=lm(data=df %>% select(-c(C1,C2,C3,C4,C5,risk)),log10(dose)~.)
plot(fit.lm)


broom::tidy(fit.lm)


