N=500
set.seed(123)
times<-runif(N,min = 10,max = 120)
ach=runif(N,min = 0.1,max = 10)
delay=runif(N,min = 1,max = 30)
k=rep(2,N)#runif(N,min = 0.01,max = 3)

m<-1.52365; s<-1.151533
# Breathing rate
#p is in l/min
p1<-c(10.8,13.1,8.2,11.6,7.2,8.6,10.9,11.0,10.8,9.9,11.4,10.6,9.8,10.9,
      9.3,8.6,12.0,12.1,12.6,9.9)
p2=c(10.46, 11.48, 13.41, 16.13,16.55)
pval=c(p1,p2)
meanp=mean(pval)
stdp=sd(pval)
pmin=meanp-stdp
pmax=meanp+stdp
pdiff=pmax-pmin
SEM = stdp/sqrt(NROW(pval))             # Standard Error
ts =  qt(c(.025, .975), df=NROW(pval)-1)   # T-Score
CI = meanp + ts*SEM                     # Confidence Intervals


logE <- truncdist::rtrunc(n = N , spec = "norm" ,a = 0 ,b = 6, mean=m, sd=s)
p <- ((CI[1]+runif(N)*CI[2]+runif(N))*0.001)/60 
# monte carlo simu for N, running it N times
# error I get sum(unlist(data))==1 is not TRUE

numerical_ODE<-function(t, state, parameters) {
  with(as.list(c(state, parameters)),{
    dC<-E/V-lambda*C
    list(dC)
  })
}


# Analytical Solution --------------------------------------------------------



analyticalODE <- function(times,E,V,lambda,C01){
  t=seq(0,NROW(times)-2) #need to convert from times seconds to 0-maxtime, to allow comparison with the ODE solver # problem if lambda is a function of time
  data.frame(times=t,
             C=E/(V*lambda)*(1-exp(-lambda*t))+C01*exp(-lambda*t))
}

# AUC function (Area Under Curve) -------------------------------------------------------


AUC <- function(x,y){ #To allow for non-uniform time-steps
  sum(diff(x[order(x)])*zoo::rollmean(y[order(x)],2))
}



# Exposure function -----------------------------------------------------
exposure<-function(logE,p,ach,times,delay,k){
  
  
  E <- (10^(logE))/3600
  #Find lambda which is the addtion of the removal rates
  lambda_v <- ach/3600 #1 ac/h, so divide by 3600 to get ac/s
  #half life of PsA 30 to 151 mins from "Viability of Pseudomonas aeruginosa in cough aerosols generated by persons with cystic fibrosis "
  half_life <- (30+ (runif(1)*121));
  half_life_s  <- half_life *60; #get in seconds
  lambda_i <- log(2)/half_life_s   #removal due to inactivation
  lambda_d  <- 0     #removal due to deposition
  lambda  <- lambda_v+lambda_i+lambda_d
  
  #Variable volume
  V <- 31.9+(runif(1)*11.8)  #area from all room sizes
  
  ####### Part 1 patient in the room
  
  t01=0
  tend1= as.numeric(times)*60 #X * 60 X is time in mins, to give seconds
  C01=0   #assume no intial concentration of CFU in the air
  
  times <- seq(t01, tend1, by = 1)
  parameters<-c(E,V,lambda)
  init<-c(C=C01)
  
  analyticalODE(times,E,V,lambda,C01)-> out1
  
  ###### Part 2 patient leaves the room
  
  #Intial conditions
  t02=tend1
  tend2= tend1 +(as.numeric(delay)*60); #X * 60 X is time in mins
  
  times <- seq(t02, tend2, by = 1)
  #C02=C1(end)    #takes the last concentration value form simulation 1
  #E0=0           #emission now 0
  
  parameters<-c(0,V,lambda)
  init<-c(C=out1$C[NROW(out1)])
  
  analyticalODE(times,0,V,lambda,out1$C[NROW(out1)])-> out2
  
  
  tmp<-
    out2%>%
    summarise(dose=AUC(times,C*p))%>%
    mutate(risk=1-exp(-dose*as.numeric(k))) #Note the multiplication instead of division, this is because of how the dose-response parameter is given
  
  
  exposure<-data.frame(C1=out1$C[NROW(out1)],
                       C2=out2$C[NROW(out2)],
                       dose=tmp$dose,
                       risk=tmp$risk
  )
  
  return(exposure)
  
  
}

df=mcmapply(FUN = exposure,logE,p,ach,times,delay,k,mc.cores = 1) %>% t()%>%
  as.data.frame() %>%
  unnest(cols=c(C1, C2, dose, risk))
  #pivot_longer(!c(dose,risk))



  
  
df=cbind(df,logE,p,ach,times,delay,k)


plot(df)


df %>% 
  ggplot()+
  geom_point(aes(y=risk,x=ach),alpha=0.2)+
  geom_smooth(aes(y=risk,x=ach),alpha=0.2,method="lm")+
  hrbrthemes::theme_ipsum()


fit.lm=lm(data=df %>% select(-c(C1,C2,risk)),log10(dose)~.)
plot(fit.lm)

broom::tidy(fit.lm)



